name: passwall2-armvirt

on:
  workflow_dispatch:

env:
  REPO_SDK: https://downloads.openwrt.org/releases/21.02.5/targets/armvirt/64/openwrt-sdk-21.02.5-armvirt-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
  CONFIG: config/armvirt.config

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download sdk
        run: |
          wget ${REPO_SDK}
          tar xf *.tar.xz
          
      - name: Get passwall2 source
        run: |
          cd openwrt-*/
          git clone https://github.com/xiaorouji/openwrt-passwall
          svn co https://github.com/xiaorouji/openwrt-passwall2/trunk/luci-app-passwall2 openwrt-passwall/
       
      - name: Load custom configuration
        run: mv -f ${CONFIG} openwrt-*/
      
      - name: Updating feeds
        run: |
          cd openwrt-*/
          ./scripts/feeds update -a
          
      - name: Installing feeds
        run: |
          cd openwrt-*/
          ./scripts/feeds install -a
      
      - name: Compile the passwall2 package
        run: |
          cd openwrt-*/
          make defconfig
          make openwrt-passwall/luci-app-passwall2/compile -j${nproc} V=w
         
      - name: Upload Package to Releases
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: 21.02.5-armvirt
          artifacts: "openwrt/bin/targets/armvirt/64/packages/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
